### ISSUE TITLE
Unable to run tdwallet in the container

### ISSUE THREAD

**Issue by maheshsenni** [padhia/docker-teradata-ttu-base#1]
When I try to run tdwallet command from the Docker container, it says `Tracing of the Teradata Wallet software is not permitted`. I am able to run BTEQ though. Any idea why this might be happening? I am using TTU version 16.20.01.00.

**Comment by padhia** [comment]
I could not reproduce the error you have been getting. Can you share your docker version and command line?

**Comment by maheshsenni** [comment]
I am running the latest available version for Mac - Docker 17.12.0-ce-mac47.

**Comment by padhia** [comment]
The issue you are facing might be specific to Docker on Mac. Unfortunately, I don't have a Mac to test. I did test this image on a Linux system with docker running at 18.01 without any issues.

If someone else replies with a fix or solution, I'll be happy to incorporate the needed changes in the Dockerfile.

**Comment by maheshsenni** [comment]
It could be specific to Mac. I tried it in a Linux machine now and it is working fine.

**Comment by padhia** [comment]
I came across this post: https://github.com/moby/moby/issues/7276#issuecomment-194139257
If you still have access to docker image on Mac, try adding `--security-opt seccomp:unconfined` to your `docker run` command and see if that resolves the issue.
