### ISSUE TITLE
Docker build fails with TeradataToolsAndUtilitiesBase/setup.bat: not found

### ISSUE THREAD

**Issue by benruco** [padhia/docker-teradata-ttu-base#2]
#7 9.554 /bin/sh: 1: TeradataToolsAndUtilitiesBase/setup.bat: not found

Followed instructions in Readme

**Comment by padhia** [comment]
That's due to a change in TTU 17.10 itself. I made changes to the `Dockerfile` so it works with TTU 17.10+. Although I haven't done any extensive testing with the docker image (because I no longer work with Teradata), I am fairly positive that the docker image would work with TTU 17.10.
